name: Supabase Keep Alive

on:
  schedule:
    # Runs at 00:00 UTC every Monday and Thursday
    # (Twice a week is safer than once a week)
    - cron: "0 0 * * 1,4"
  workflow_dispatch: # Allows you to run it manually from the Actions tab for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          # This command requests a single row from the REST API.
          # We use 'curl' so no extra code/dependencies are needed.

          # REPLACE 'users' WITH ANY VALID TABLE NAME IN YOUR DATABASE
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            "${{ secrets.COCOSUPABASEURL }}/rest/v1/maps?select=*&limit=1" \
            -H "apikey: ${{ secrets.COCOSUPABASEKEY }}" \
            -H "Authorization: Bearer ${{ secrets.COCOSUPABASEKEY }}")

          if [ "$response" -eq 200 ]; then
            echo "Success! Supabase is awake. HTTP 200"
          else
            echo "Failed with HTTP $response"
            exit 1
          fi
